### ISSUE TITLE
LoginPage - estilização

### ISSUE THREAD

**Issue by rosanarezende** [future4code/4eddit-sagan-3#8]
**Definição de feito**: LoginPage com layout estático usando Material-UI e com botões de rota apontando para as páginas corretas

- [x] layout estático com Material-UI

- [x] botões de rotas funcionando

![Untitled (3)](https://user-images.githubusercontent.com/59846340/78026808-9bf05780-7332-11ea-8d46-4cf65893d59e.png)

**Comment by EloisaFagundes** [comment]
![Untitled (3)](https://user-images.githubusercontent.com/59846340/78026699-706d6d00-7332-11ea-9e86-f9bf2a311dc2.png)
