### ISSUE TITLE
RegisterPage - estilização

### ISSUE THREAD

**Issue by rosanarezende** [future4code/4eddit-sagan-3#9]
**Definição de feito**: RegisterPage com layout estático usando Material-UI e com botões de rota apontando para as páginas corretas

- [x] layout estático com Material-UI

- [x] botões de rotas funcionando

![Untitled (1)](https://user-images.githubusercontent.com/59846340/78026885-be827080-7332-11ea-96d0-0f859cf592cb.png)

**Comment by LuanSchneider** [comment]
egrehe0[rs
